In [1]:
import pandas as pd
import numpy as np
import re
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv(r"C:\Users\Abdul\OneDrive\Documents\Ultimate AI Mastery BootCamp\NLP\Session 28,29&30\language_detect.csv")

In [4]:
data

,Text,Language
0,"Nature, in the broadest sense, is the natural...",English
1,"""Nature"" can refer to the phenomena of the phy...",English
2,"The study of nature is a large, if not the onl...",English
3,"Although humans are part of nature, human acti...",English
4,[1] The word nature is borrowed from the Old F...,English
...,...,...
10332,ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...,Kannada
10333,ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...,Kannada
10334,ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...,Kannada
10335,ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...,Kannada


In [3]:
data['Language'].value_counts()

Language
English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: count, dtype: int64

In [4]:
X = data["Text"]
y = data["Language"]

In [6]:
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[3 3 3 ... 9 9 9]


In [7]:
import re
data_list = []
for text in X:
    text = re.sub(r'[!@#$(),"\n%*?:;~`0-9]', ' ', text)
    text = text.lower()
    data_list.append(text)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv.fit_transform(data_list).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10337, 39404))

In [12]:
cv.vocabulary_

{'nature': 16409,
 'in': 12317,
 'the': 24351,
 'broadest': 3298,
 'sense': 21944,
 'is': 13158,
 'natural': 16399,
 'physical': 18429,
 'material': 15291,
 'world': 27052,
 'or': 17481,
 'universe': 25331,
 'can': 3556,
 'refer': 20371,
 'to': 24541,
 'phenomena': 18394,
 'of': 17100,
 'and': 1092,
 'also': 881,
 'life': 14507,
 'general': 10459,
 'study': 23280,
 'large': 14184,
 'if': 12075,
 'not': 16751,
 'only': 17341,
 'part': 17928,
 'science': 21712,
 'although': 904,
 'humans': 11836,
 'are': 1621,
 'human': 11825,
 'activity': 290,
 'often': 17153,
 'understood': 25260,
 'as': 1769,
 'separate': 21977,
 'category': 3730,
 'from': 9980,
 'other': 17608,
 'word': 27041,
 'borrowed': 3187,
 'old': 17203,
 'french': 9936,
 'derived': 6191,
 'latin': 14213,
 'natura': 16397,
 'essential': 8565,
 'qualities': 19885,
 'innate': 12700,
 'disposition': 6850,
 'ancient': 1090,
 'times': 24494,
 'literally': 14628,
 'meant': 15355,
 'birth': 3035,
 'philosophy': 18408,
 'mostly': 16003

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=0)

In [19]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [23]:
y_pred = model.predict(x_test)
y_pred

array([13, 16, 12, ...,  3, 13,  5], shape=(2068,))

In [25]:
def predict(text):
    x = cv.transform([text]).toarray()
    lang = model.predict(x)
    print(lang)
    lang = le.inverse_transform(lang)
    print(lang)
    print("The langauge is in",lang[0])

In [26]:
predict("Hello and welcome Friend")

[3]
[3]
The langauge is in 3


In [27]:
predict("यह लोगों के लिए स्पष्ट बयान और डर रखनेवालों के लिए मार्गदर्शन और उपदेश है")

[7]
[7]
The langauge is in 7


In [28]:
predict("மேலும் கவனமாகப் பழைய அமைப்புக்களைக் காக்கும் மரபினாலும் பழங்கால இலக்கிய நடை கூட மக்களால் புரிந்து கொள்ளும் நிலையில் உள்ளது. எடுத்துக்காட்டாக")

[15]
[15]
The langauge is in 15


In [29]:
predict("ಅತ್ಯಂತ ಹೆಚ್ಚು ಮಂದಿ ಮಾತನಾಡುವ ಭಾಷೆಯೆಂಬ ನೆಲೆಯಲ್ಲಿ ಇಪ್ಪತೊಂಬತ್ತನೆಯ ಸ್ಥಾನ ಕನ್ನಡಕ್ಕಿದೆ. ೨೦೧೧ರ ಜನಗಣತಿಯ ಪ್ರಕಾರ ಜಗತ್ತಿನಲ್ಲಿ ೬.೪ ಕೋಟಿ ಜನರು ಕನ್ನಡ ಮಾತನಾಡುತ್ತಾರೆ ಎಂದು ತಿಳಿದುಬಂದಿದೆ")

[9]
[9]
The langauge is in 9


In [30]:
predict("merhaba ve hoş geldin dosto")

[16]
[16]
The langauge is in 16


In [31]:
predict("παράδειγμα")

[6]
[6]
The langauge is in 6


In [32]:
predict("Hej då! Vi ses! Vi hörs!")

[14]
[14]
The langauge is in 14


In [33]:
import pickle
pickle.dump(model, open('ldmodel.pkl','wb'))

In [34]:
pickle.dump(cv, open('ldvector.pkl','wb'))